server:
  port: 8001
spring:
  application:
    name: FEBS-Register
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/