server:
  port: 8002

spring:
  redis:
      database: 0
      host: localhost
      port: 6379
      jedis:
        pool:
          min-idle: 8
          max-idle: 500
          max-active: 2000
      password: zyiscool
  application:
    name: FEBS-Auth
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
